### ISSUE TITLE
Override default basic auth with single connector API key

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1521]
## Bug Description
The implicit default configuration for the connectors framework is:
```
elasticsearch:
  host: http://localhost:9200
  username: elastic
  password: changeme
  api_key: null
connectors: []
```
and the default explicit configuration is:
```
```

Kibana provides a block to paste when you create a new connector, of:
```
connectors:
  -
    service_type: <service_type>
    connector_id: <id>
    api_key: <api_key>
```

If you paste that block, and only that block, into the explicit config (`config.yml`)

You provide Elasticsearch credentials for the _single connector_ but not the whole framework. The top-level `elasticsearch.username` and `elasticsearch.password` will still be using the defaults.

### To Reproduce
1. Start with a fresh clone
2. create a connector on cloud
3. paste only what kibana tells you to paste
4. get a 401 error because `elastic:changeme` doesn't work for your deployment

## Expected behavior
Since the user has provided an API Key, we should use that API key.
This is not true if there are multiple connectors configured. In that case, an explicit set of top-level credentials will be required and will fall back to the defaults if necessary. 

## Environment
8.10.0-BC.1

## Additional context
[slack thread](https://elastic.slack.com/archives/C01795T48LQ/p1692806214826899?thread_ts=1692789088.115089&cid=C01795T48LQ)
