### ISSUE TITLE
[Slack] Queue Full and sync hangs in progress

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors#1538]
## Bug Description
What I can observe is:
1, The ingestion process starts with an exception:

```
[FMWK][04:10:29][DEBUG] [Sync Job id: jR4IMIoBc5eOdeh49EBK, connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Scanning existing index search-xxx-slack
Task exception was never retrieved
future: <Task finished name='Task-6377890' coro=<Extractor.run() done, defined at /app/connectors/es/sink.py:342> exception=QueueFull('MemQueue has been full for 60.0892s. while timeout is 60s.')>
Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 433, in get_docs
    await self.queue.put(
  File "/app/connectors/utils.py", line 295, in put
    raise result
asyncio.queues.QueueFull: MemQueue has been full for 60.0914s. while timeout is 60s.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 346, in run
    await self.get_docs(generator)
  File "/app/connectors/es/sink.py", line 445, in get_docs
    await self.queue.put("FETCH_ERROR")
  File "/app/connectors/utils.py", line 295, in put
    raise result
asyncio.queues.QueueFull: MemQueue has been full for 60.0892s. while timeout is 60s.
```

This exception will not break the sync.

2. I see many throttling errors

```
[FMWK][04:12:04][DEBUG] [Sync Job id: jR4IMIoBc5eOdeh49EBK, connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Rate Limited by Slack: waiting at least 10 seconds before retry...
[FMWK][04:12:14][DEBUG] Retrying (1 of 3) with interval: 1.0 and strategy: LINEAR_BACKOFF
3, After a while I start seeing timeout errors and queue full messages:
[FMWK][04:40:55][DEBUG] Queue Full
[FMWK][04:40:56][DEBUG] Queue Full
[FMWK][04:40:57][DEBUG] Queue Full
[FMWK][04:40:58][CRITICAL] [Sync Job id: jR4IMIoBc5eOdeh49EBK, connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] The document fetcher failed

[FMWK][04:47:59][ERROR] Exception found for task Task-6556137: Connection timeout caused by: ConnectionTimeout(Connection timeout caused by: TimeoutError())
4. After that it seems like the connector forgets that is syncing, I see no more errors but "no idle jobs found" messages.
[FMWK][05:20:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
[FMWK][05:20:40][DEBUG] Polling every 30 seconds for Job Scheduling Service
[FMWK][05:20:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Status is Status.CONNECTED
[FMWK][05:20:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Filtering is in state valid, skipping...
[FMWK][05:20:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
[FMWK][05:21:10][DEBUG] Polling every 30 seconds for Job Scheduling Service
[FMWK][05:21:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Status is Status.CONNECTED
[FMWK][05:21:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Filtering is in state valid, skipping...
[FMWK][05:21:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
[FMWK][05:21:32][DEBUG] Start cleaning up orphaned jobs...
[FMWK][05:21:32][DEBUG] No orphaned jobs found. Skipping...
[FMWK][05:21:32][DEBUG] Start cleaning up idle jobs...
[FMWK][05:21:32][DEBUG] No idle jobs found. Skipping...
[FMWK][05:21:40][DEBUG] Polling every 30 seconds for Job Scheduling Service
[FMWK][05:21:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Status is Status.CONNECTED
[FMWK][05:21:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Filtering is in state valid, skipping...
[FMWK][05:21:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
[FMWK][05:22:10][DEBUG] Polling every 30 seconds for Job Scheduling Service
[FMWK][05:22:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Sending heartbeat
[FMWK][05:22:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Status is Status.CONNECTED
[FMWK][05:22:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Filtering is in state valid, skipping...
[FMWK][05:22:10][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
[FMWK][05:22:40][DEBUG] Polling every 30 seconds for Job Scheduling Service
[FMWK][05:22:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Status is Status.CONNECTED
[FMWK][05:22:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] Filtering is in state valid, skipping...
[FMWK][05:22:40][DEBUG] [Connector id: HHl324kBOUh0jxx0nBuF, index name: search-xxx-slack] 'full' sync scheduling is disabled
```

The UI shows in progress.

### To Reproduce
Sync to a big number of channels

## Expected behavior
Sync should happen

**Comment by danajuratoni** [comment]
Fresh additional context: _the issue appeared with ~ 400 channels and some of them with Slack bot providing multiple updates each hour._

**Comment by llermaly** [comment]
Attaching configuration used:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: connector-slack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: connector-slack
        app.kubernetes.io/component: elastic-connector
    spec:
      containers:
        - name: connector-slack
          image: docker.elastic.co/enterprise-search/elastic-connectors:8.10.0.0-SNAPSHOT
          imagePullPolicy: Always
          command:
            - /app/bin/elastic-ingest
          args:
            - -c
            - /config/config.yml
            - --debug
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: ca-certs
              mountPath: /etc/eck/certificates
              readOnly: true
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: config-volume
          configMap:
            name: connector-slack-config
        - name: ca-certs
          secret:
            secretName: elasticsearch-xxx-es-http-certs-public
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-slack-config
data:
  config.yml: |-
    elasticsearch:
      ssl: true
      verify_certs: true
      ca_certs: /etc/eck/certificates/ca.crt
      host: https://elasticsearch-xxxxxx-es-http:9200
      api_key: "XXXXXXXXXX"
      bulk:
        queue_max_size: 1024
        queue_max_mem_size: 25
        display_every: 100
        chunk_size: 1000
        max_concurrency: 5
        chunk_max_mem_size: 5
        concurrent_downloads: 10
      request_timeout: 120
      max_wait_duration: 120
      initial_backoff_duration: 1
      backoff_multiplier: 2
      log_level: debug

    service:
      idling: 30
      heartbeat: 300
      max_errors: 20
      max_errors_span: 600
      max_concurrent_syncs: 1
      job_cleanup_interval: 300
      log_level: DEBUG

    # connector information
    connector_id: "xxxxxxx"
    service_type: slack

    sources:
      slack: connectors.sources.slack:SlackDataSource
```
