### ISSUE TITLE
Unable to connect! Cannot connect to host host.docker.internal:9200 ssl:default

### ISSUE THREAD

**Issue by Nodirbek3d** [elastic/connectors#1826]
I have following docker-compose:
```
version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: yolla-food-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - yf-network
    volumes:
      - yf-es:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.10.2
    container_name: yolla-food-kibana
    ports:
      - "5601:5601"
    networks:
      - yf-network
    depends_on:
      - elasticsearch
    volumes:
      - yf-kibana:/usr/share/kibana/data

  pg_connector:
    image: docker.elastic.co/enterprise-search/elastic-connectors:8.10.2.0
    container_name: yolla-food-pg-connector
    networks:
      - yf-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
    command: [ "/app/bin/elastic-ingest", "-c", "/config/config.yml" ]
    volumes:
      - ./connectors-config:/config

  logstash:
    image: logstash:8.10.2
    container_name: yolla-food-logstash
    ports:
      - "5001:5000"
    networks:
      - yf-network
    depends_on:
      - elasticsearch

  redis:
    image: redis:7.2.2
    container_name: yolla-food-redis
    ports:
      - "6379:6379"
    networks:
      - yf-network
    volumes:
      - yf-redis:/data

  postgres:
    image: postgres:15.4
    container_name: yolla-food-postgres
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    environment:
      POSTGRES_USER: yolla_admin
      POSTGRES_PASSWORD: yadmin123123
      POSTGRES_DB: yolla
    ports:
      - "5432:5432"
    networks:
      - yf-network
    volumes:
      - yf-pg:/var/lib/postgresql/data
      - ./custom-postgresql.conf:/etc/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: yolla-food-pg-admin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: Test123123@
    volumes:
      - yf-pgadmin:/var/lib/pgadmin

networks:
  yf-network:
    driver: bridge

volumes:
  yf-pg:
  yf-es:
  yf-kibana:
  yf-redis:
  yf-pgadmin:
```
config.yml looks like this:
```
elasticsearch.host: https://host.docker.internal:9200
elasticsearch.api_key: api-ley-from-kibana==

connectors:
  -
    connector_id: id
    service_type: postgresql
    api_key: api-ley-from-kibana==
```
when I check connector logs I see:
```
[FMWK][18:29:07][INFO] Waiting for NodeConfig(scheme='https', host='host.docker.internal', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 32 secs)

[FMWK][18:29:08][ERROR] Could not connect to the server

[FMWK][18:29:08][ERROR] Cannot connect to host host.docker.internal:9200 ssl:default [None]

[FMWK][18:29:40][INFO] Waiting for NodeConfig(scheme='https', host='host.docker.internal', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 64 secs)

[FMWK][18:29:40][ERROR] Could not connect to the server

[FMWK][18:29:40][ERROR] Cannot connect to host host.docker.internal:9200 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)]

[FMWK][18:30:44][CRITICAL] https://host.docker.internal:9200 seem down. Bye!

[FMWK][18:30:44][INFO] Bye
```
I have no idea how to fix this? is it because of self-signed certificate that elasticsearch uses? Is there anything I am doing wrong?
