### ISSUE TITLE
Allow insecure HTTPS

### ISSUE THREAD

**Issue by dodie** [elastic/connectors#2491]
### Problem Description

When I try to connect to an Elasticsearch cluster with HTTPS, it is only possible to do so with a certificate with valid CA that is set up via the `ca_certs` configuration option. In my case, the target Elasticsearch is a test instance used for trials only, but it only accepts HTTPS traffic. For ad-hoc tests it would be convenient to access it without verifying the certificates. (Similarly to how `curl` can be used with the `--insecure` flag.)

### Proposed Solution
Allow setting the `verify_certs` property via the connector `config.yml`, e.g.:

```
connectors:
-
  ...

elasticsearch:
  host: "https://<ES_HOST>:9200"
  verify_certs: false    # Defaults to true
  api_key: "..."
```

### Additional Context
As workaround to allow insecure access via HTTPS, one might locally change the following flag to False:

https://github.com/elastic/connectors/blob/bed2e63cd2c01a15e33c13024b7a9aac5935d1be/connectors/es/client.py#L93
